apiVersion: apps/v1
kind: Deployment
metadata:
  name: country-service
  labels:
    app: country-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: country-service
  template:
    metadata:
      labels:
        app: country-service
    spec:
      containers:
        - name: country-service
          image: bentechmusili/country-service:1.0
          imagePullPolicy: Always

          ports:
            - containerPort: 80

          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 20